# Generated by Django 6.0.3 on 2026-03-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('UPI', 'UPI'), ('CARD', 'CARD')], default='COD', max_length=20),
            preserve_default=False,
        ),
    ]
